name = "Psi4Calculator"
uuid = "e2b7ad92-acfe-472f-ae48-51c2aed5b591"
authors = ["Teemu Järvinen <teemu.j.jarvinen@gmail.com> and contributors"]
version = "0.1.0-DEV"

[deps]
AtomsBase = "a963bdd2-2df7-4f54-a1ee-49d51e6be12a"
PotentialCalculation = "76415700-ec45-11e8-0f65-f1df3c899b21"
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"

[compat]
AtomsBase = "0.3"
PotentialCalculation = "0.6"
PythonCall = "0.9"
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
